### ISSUE TITLE
Pretrained VG Detector: This item was deleted!

### ISSUE THREAD

**Issue by Kilichbek** [nocaps-org/image-feature-extractors#3]
When I wanted to download the pretrained model, it shows me : "This item was deleted
You might be able to find it in your deleted files. If it's not there, try asking the person who shared it with you."

**Comment by jpainam** [comment]
I confirm. It is deleted. Can't find it in the deleted files.  Please,   can you share it again?

Thank you.

**Comment by dexter1691** [comment]
The model is the same from https://github.com/peteanderson80/bottom-up-attention
Youn can download it here: 
 https://www.dropbox.com/s/5xethd2nxa8qrnq/resnet101_faster_rcnn_final.caffemodel?dl=1
